### ISSUE TITLE
请问能不能出WINDOWS的wheel

### ISSUE THREAD

**Issue by cssuperman** [AlongWY/TransformerEngine_wheels#1]
我在WIN11 下,尝试了在CUDA 11.8~12.6 TORCH 2.4 python3.12各种版本环境下编译都失败了,没办法,请问能不能出WINDOWS的wheel能让我安装?

**Comment by AlongWY** [comment]
在 [TransformerEngine #1076](https://github.com/NVIDIA/TransformerEngine/issues/1076) 中提到暂时没有 Windows 的支持计划，也就是说 TransformerEngine 现在不支持 Window 平台。

**Comment by cssuperman** [comment]
原来如此,谢谢,你知道在windows上有什么类似te的能进行fp8加速的其他套件吗

**Comment by AlongWY** [comment]
可以看看 Deepspeed
